### ISSUE TITLE
Popups for single entries

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#10]
With all the information to an entry and a big field for displaying the memo. Fits #6 somewhat.

**Comment by kiliankoe** [comment]
Just wondering if this is really the way to go or if we should directly head towards #42? A modal is pretty, nothing else. A single page would be a lot more useful in the long run.

**Comment by kiliankoe** [comment]
Maybe keep this as somewhat of an _apple-like_ quickview mode (with a button showing an icon like [this](http://fortawesome.github.io/Font-Awesome/icon/eye/) maybe?) and display the modal in this case. But this is out of scope for the first prototype.

**Comment by lucaswo** [comment]
closed by discussion
