### ISSUE TITLE
API

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#11]
Because why not... Really isn't that difficult. But definitely not a pressing todo ;)

**Comment by preip** [comment]
It might be me being oblivious and all, but what is the meaning of this issue?

**Comment by kiliankoe** [comment]
Creating an API, sooner or later^^ Although I was playing with the idea of tackling this rather early so we could actually dogfood it to ourselves. There's probably no longterm use for this though, so that idea isn't worth all too much.

**Comment by kiliankoe** [comment]
Kicked out the API in 1e99899faf488a749252f35ee47d495dde2e9ae9, isn't worth it.
