### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#14]
Import for CSV should be working at the very least.

**Comment by preip** [comment]
highjacked^^ - I'm working on it and hopefully it will soon be done.

**Comment by preip** [comment]
Well the import is slowly coming along. CSV files are now validated for the correct format, but the data is still not written into the database. What do you think, should the results of the import be displayed on a single page (likely one for errors and one for success) or inside the main import page (like it's the case now)?

**Comment by kiliankoe** [comment]
Just as a note: http://database-import-scriptor.appspot.com/

**Comment by preip** [comment]
pah, where is the fun in that.^^
This would totally rob us of the chance to write messy code for our own importer.
Besides, import may already be working more or less. We'll find out as soon as I get around to finally test the thing.

**Comment by preip** [comment]
yay - import is finally working. I should have gotten around finishing this sooner...
Well, the input still needs to be sanitized and the code doesn't take into account what an asynchronous bitch node.js is, but working is working...
I also added an example csv file in case someone else wants to try.

**Comment by kiliankoe** [comment]
> what an asynchronous bitch node.js is

so fucking true...

**Comment by preip** [comment]
well, changing the database to having no more email en phone tables made also the import a lot easier. What a luck that I had already implemented the import for the old, more complicated variant...

**Comment by preip** [comment]
So, the new database layout is supported by the import, the async calls are handled appropriate, and even the input seems to be sanitized. I tried to insert some DROP TABLE persons into the database and everything went fine.
If someone else want's to test this, that would be much appreciated. Otherwise the import is DONE (yay).
