### ISSUE TITLE
Sanitize data input or use prepared sql-statements

### ISSUE THREAD

**Issue by SaschaPeukert** [kollemate/kolledata#17]
Because otherwise this will be a big security failure

**Comment by kiliankoe** [comment]
I'm just going to leave this here, for reference: https://github.com/felixge/node-mysql#escaping-query-values

**Comment by kiliankoe** [comment]
True prepared statements (not just _well formatted statements_) [aren't supported](https://github.com/felixge/node-mysql/issues/274) by the node-mysql module, but there's also [node-mysql2](https://github.com/sidorares/node-mysql2), which claims to be api compatible. We should take a look at this.

**Comment by SaschaPeukert** [comment]
Reminder:
Inserting the following in one of the input fields will get the server to crash.

```
'<script type="text/javascript">
          alert("Hallo Welt!");
</script>'
```

We need to sanitize the input und check our sql-quoting because the values of the parameters should never be able to throw sql-exceptions

**Comment by kiliankoe** [comment]
I remember seeing this crash the server, but I can't for the life of me reproduce this currently... Everything just works like expected. Anyone please feel free to reopen this whenever it seems to have any unwanted effects.
