### ISSUE TITLE
Don't crash if there is no database

### ISSUE THREAD

**Issue by heisig** [kollemate/kolledata#35]
app.js crashes if there is no database, there should just be a error message for the user

**Comment by kiliankoe** [comment]
Another option would be to create the database if it's not found when starting.

**Comment by kiliankoe** [comment]
Same goes for every single `if (err) throw err` with the database queries. Show these errors in the form of alerts to the user and just don't display any database data if it's not available.

**Comment by preip** [comment]
This should now be fixed, database error no redirect to a special error page. The http state for that error is 500, but the message is different to the generic error.
I would appreciate if someone else could also test this an confirm that it's working as intended.

As a additional note, I think it wouldn't be a good idea to create the database if it's not present. In case of an error I think this will most likely cause more harm than good.

**Comment by kiliankoe** [comment]
Works. Although the error is not displayed when no MySQL server is running, only when it is but the kolledata database is not found.

> As a additional note, I think it wouldn't be a good idea to create the database if it's not present. In case of an error I think this will most likely cause more harm than good.

Doing it similar to the setup script with a `CREATE IF NOT EXIST` should be the way of doing it. If the database errors, no data will be created, if it does work, it won't be overwritten. Handling the error is fine, but this is in my opinion still the right thing to do.

**Comment by kiliankoe** [comment]
So this is all pretty and nice since we've got error handling. Never bothered to check :P
