### ISSUE TITLE
Sanitizing fields (missing "http://", invalid mails etc.)

### ISSUE THREAD

**Issue by sjmielke** [kollemate/kolledata#38]
And why would they unless we would automatically add such a prefix while inserting values in the database or displaying them on the page.

**Comment by kiliankoe** [comment]
I'd rename this issue to something in the direction of generally _sanitizing_ email and website fields. Check if it's a valid mail, check if it's a valid url (and add http:// if it's missing) and maybe the phone number (when it's added) as well? 

That way there'd be clean data in the database and everyone would be happy :P

**Comment by sjmielke** [comment]
Sounds like the best idea.
