### ISSUE TITLE
Search (on Firefox)

### ISSUE THREAD

**Issue by SaschaPeukert** [kollemate/kolledata#40]
While using firefox (on windows) the search-function will behave a little bit odd. After every typed letter, the whole entrys will pop up again (screen flashing white)

Doesn't happen in Chrome.

**Comment by kiliankoe** [comment]
Can't reproduce with Firefox 29.0.1 under OS X.

**Comment by heisig** [comment]
Doesn't happen here on Linux with Firefox 29.0.1

**Comment by kiliankoe** [comment]
Can't reproduce with Firefox 29.0.1 under Win 8.1 (no VM) either^^ It's only your computah :D

(By the way, site looks and works fine in IE 9.0, which is awesome)

**Comment by sjmielke** [comment]
Firefox 29.0.1, Arch Linux, no problems.

**Comment by kiliankoe** [comment]
Can't reproduce under **Win 7** with Firefox 29.0.1 either.
