### ISSUE TITLE
Single pages for entries

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#42]
Seeing how much information there can be for an entry, a simple modal might only work as a quick preview, but something like complete pages for single entries for showing all the data would be a good addition.

**Comment by kiliankoe** [comment]
2d389caf41bcb86dcb9d8dfabca4eee24bceb565 is a start. Still needs some kind of good layout, all the new information (from the recent schema updates), a good way of editing stuff (maybe even edit single fields?) and a button to delete an entry. 

Maybe try and keep most of the information pretty compact at the top so that most of the page stays fairly empty for the memo.

**Comment by lucaswo** [comment]
Now with a button, that let you reach a person's site from the persons overview.

**Comment by kiliankoe** [comment]
Single pages exist, are somewhat functional and will be improved in the future. I'm closing this.
