### ISSUE TITLE
show 404 errors

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#46]
The browser currently either receives no data or displays 'Cannot GET /random' on non-existing root pages. The server should send the correct http code (404) in this case and maybe even display a pretty page.

**Comment by preip** [comment]
I already tried to do this several weeks ago, but it didn't work and I got carried away. Nonetheless I would still like to solve this, just in case someone else is also working on this. I will assign it to me as soon as I get something meaningful done.

**Comment by preip** [comment]
404 Error Handling done!
