### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#48]
Having only the UI in German just doesn't feel right ;)

This would also be a great opportunity to trade a lot of the of the labels/buttons for icons from fontawesome (or something similar).

**Comment by preip** [comment]
Multi-language support FTW... Now you can have the best of both worlds: Icons and labels in whatever language you want them to be.

**Comment by kiliankoe** [comment]
This is pretty damn cool!

**Comment by kiliankoe** [comment]
todo for this: pull the strings on all pages from the corresponding json file and find out how to set the language based on the user's browser/system language

**Comment by preip** [comment]
Well there is also the tiny little problem of setting the language for each user individually and not globally, like it's the case for now. But I got that on the radar, I'm just not sure what would be the best way to implement this. One basically needs to pass a custom language object through every page the user is visiting.

**Comment by kiliankoe** [comment]
That's what I meant by checking the user's browser/system language. It's how most sites on teh interwebs handle this.

**Comment by preip** [comment]
Everything (except the about page and the delete company confirm dialog) has now multi-language support. I guess that would mean this issue can be closed?

**Comment by kiliankoe** [comment]
Awesome stuff.
