### ISSUE TITLE
Detailed installation instructions

### ISSUE THREAD

**Issue by preip** [kollemate/kolledata#49]
Should we make more detailed installation instructions that the current ReadMe for non tech-savvy people? Also for different platforms?
The main question is: How difficult will it be for everybody to install everything so it will simply work, no tweaks required?

**Comment by kiliankoe** [comment]
Non-tech savvy people should not be _installing_ this. And even if so, this is pretty standard stuff for any node application out there. We could have a slightly more detailed install guide, but it's probably not going to be a lot more than the current readme.
