### ISSUE TITLE
Google frei

### ISSUE THREAD

**Issue by frankhedecke** [kollemate/kolledata#5]
Wenn ich das richtig sehe, nutzen wir Google-Web-Fonts. Ich würde mehr auf Privatssphäre achten.

**Comment by kiliankoe** [comment]
OpenSans wird von Bootstrap nachgeladen, das stimmt. Hässlich oder der de facto standard Weg um Fonts einzubetten...?

**Comment by frankhedecke** [comment]
Können wir auch später fixen - sollten wir nur vor der Ürgabe machen.

**Comment by preip** [comment]
Is this still relevant?

**Comment by kiliankoe** [comment]
Theoretically, it's at least something we should think about. I prefer pulling content from a CDN instead of providing it locally, but you are sending some data to a company like Google, which is a tiny privacy concern Frank is worried about.

**Comment by lucaswo** [comment]
closed by common sense

**Comment by kiliankoe** [comment]
Hello common sense, [I'm dad](http://reddit.com/r/dadjokes).
