### ISSUE TITLE
Use transactions to communicate with the database

### ISSUE THREAD

**Issue by SaschaPeukert** [kollemate/kolledata#50]
Always use Transactions. So you can revert past operations, if following operations fail.

This is a very serious todo!

**Comment by SaschaPeukert** [comment]
This Issue does not apply to the create-statements in the setup script. After some very frustrating experiments, i found out that they will always trigger an implicit autocommit (thanks mysql -.-).
http://dev.mysql.com/doc/refman/5.0/en/implicit-commit.html

But still everything else should be embedded in a transaction.

**Comment by kiliankoe** [comment]
Looks to be rather simple to implement -> https://github.com/felixge/node-mysql#transactions
