### ISSUE TITLE
E-Mails - Why the discrepancy?

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#51]
A person isn't allowed to have just two e-mail addresses, but has to have an unlimited amount. For some reason however this rule doesn't count for companies, which have exactly two addresses directly in their table... Why?

My vote's still for exactly two e-mail addresses for everybody, persons and companies alike. Two is more than enough, makes a lot of things easier (a LOT). The csv file we have shows that entries have just one email, so we're definitely not missing out on anything.

**Comment by SaschaPeukert** [comment]
As i told you earlier, this is the best design because i has the most potential. Even if you don't support more than two addresses in the frontend now, you could do that later without any problems by sticking to this design. It would be very bad database design to enforce such random (and remote from everyday life) rules like "nobody should have more than two emailaddresses", especially if its not that hard to implement.

btw: i have over two addresses myself :-)

**Comment by preip** [comment]
But still the question persists why for companies that random rule is perfectly fine. Should the same not apply to companies too, at least for the sake of consistency. Just saying...

**Comment by kiliankoe** [comment]
So I could theoretically save all of my over 9.000 e-mail addresses for myself, which is great, but that's ridiculous. It's just like a phone number, people can have a shit-ton of these, but I'm still only looking for the one that's current and will get me an answer if I call it. Maybe save two, one for business and one for personal (no such thing as a mobile e-mail address), but everything else is bloat and really not necessary. If it changes, I'd rather edit than add a new one, because in that case I'd forget which one to write to next time.

**Comment by lucaswo** [comment]
I found a workaround for the email problem in the person view. I'm sitting on it, but this still don't resolve our fundamental discussion.

**Comment by preip** [comment]
@SaschaPeukert: sooo?

**Comment by kiliankoe** [comment]
Any updates? I'm still for having just two addresses, see my arguments above. But it would be nice clearing this as milestone 1 just isn't doable without closing this issue ;)

**Comment by kiliankoe** [comment]
Could we please make a decision here. If not, I'm just going to go ahead and change this. This is literally the only thing holding at the least first prototype back. And it's frustrating. 

I'm sticking with two email addresses per person which are in the `kd_person` table with their respective person instead of being linked from another table. This is what companies have at the moment. Having more than two addresses is completely unnecessary and not worth it. The argument for this has nothing to do with being 'future-proof', it really just is unnecessary saving more than two addresses for one person.

Now let's get on with this.

![lemon](http://media.giphy.com/media/QSdauORwsTtSM/giphy.gif)

**Comment by lucaswo** [comment]
Theoretical it should work after 4468afa013c4f1a2da34e3a31c5fb8c49e832abc. The only thing we need is some sort of dynamic entry foo on the editPerson page, so you can add more fields, in which you can write the email addresses.

**Comment by kiliankoe** [comment]
The main problem I have with this is not that it's impossible to do it this way, it's just unnecessary and more importantly inconsistent as companies have their mail addresses as two fields right in their entry.

**Comment by lucaswo** [comment]
Let's make a craaaaaaaaaaaaazy suggestion here: Why don't we ask the future user about that? I know it sounds mad, but sometimes the user knows what he wants. ;)
But seriously, we really should ask kollemate about this, since we can't settle the argument.

**Comment by kiliankoe** [comment]
![](http://i.imgur.com/jZPp3M0.png)

**Comment by kiliankoe** [comment]
\o/
