### ISSUE TITLE
Department field for company table

### ISSUE THREAD

**Issue by preip** [kollemate/kolledata#60]
The company table in the database needs a 'department' field so i can match the 'Abteilung' field in the csv header we got to that field during the import. While I could add it myself, I would prefer if our database expert does it, to prevent me from breaking anything.^^
I took the liberty of already assigning that task to him.

These of course also means we have to update the company pages to display the new field.

**Comment by preip** [comment]
Well, I just noticed, there already is a department field in the persons table which makes of course much more sense than having one in the company table...
So ignore me me and good work Sascha.^^

I presume creating an extra table for the departments of a company which we would use in the persons table would be overkill and unnecessary?

**Comment by kiliankoe** [comment]
> I presume creating an extra table for the departments of a company which we would use in the persons table would be overkill and unnecessary?

Probably. Might be an idea for a huge crm system, but not for us.

And since updating the companies page is it's own issue -> #25, I'm just going to go ahead and close this ;)
