### ISSUE TITLE
Person's edit button moves down on page refresh

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#61]
This is how it should look:

![](http://i.imgur.com/rPuX6lu.png)

After refreshing a person's page, this is what it looks like instead:

![](http://i.imgur.com/pOLyazy.png)

A reload of a page fixes that, but wat?

**Comment by lucaswo** [comment]
Apparently this bug doesn't appear anymore.....

**Comment by kiliankoe** [comment]
Can confirm in Safari and Chrome... Who knows what happened here.
