### ISSUE TITLE
Insert does not check for duplicates in companies

### ISSUE THREAD

**Issue by lucaswo** [kollemate/kolledata#63]
If I insert a person two consecutive times, the person/company is imported as two different ones, but there should be only one.

**Comment by kiliankoe** [comment]
Let's not do this. It's really hard to check whether an entry is a duplicate or not and if a user really wants to be able to add them, they should be able to. Same actually goes for the import, importing twice adds duplicate entries, so you just shouldn't do it.

As long as we know that this is not supposed to be working with thousands of entries, this is just not worth it.
