### ISSUE TITLE
Error handler is eating jade errors

### ISSUE THREAD

**Issue by kiliankoe** [kollemate/kolledata#64]
``` js
app.use(errorController.errDb);
app.use(errorController.generic);
```

These two lines in the `app.js` are eating our jade error messages leading to very undescriptive messages like `Cannot GET /companies`. That's not very awesome and makes jade incredibly hard to debug.

@preip You're the only one who knows how the error handling really works. Anything you can do about this?

**Comment by lucaswo** [comment]
And creating cannot get errors, which do not occur, if the error handlers are disabled.

**Comment by preip** [comment]
Well as a start just disable them for the moment.

I can imagine that they are preventing the jade error page from appearing, but i can't see how they can possibly create get errors.
@lucaswo are you sure you got that one right? I would guess the get errors are still there without the error handlers, but just catched at another place.

**Comment by lucaswo** [comment]
I didn't really pinpoint the error, but with the error handling in comments, the error did not appear. On the other hand, whenever I tried to access the person view with error handling activated, I got a GET error.
After working around some stuff in the jade, i could use your error handling, so probably the error was in fact catched somewhere else.

**Comment by preip** [comment]
So, after looking into the problem a little more, I'm convinced everything works like it should be. The error handlers are for handling user errors (like accessing the wrong url) or environment errors (like a missing database). They are not (and can't be) for handling programming errors (like a wrong jade file). They exists so prevent the user from seeing the internal server state and showing them a nice little error page. As long as we are developing, we should therefore disable them so programming errors are exposed to us. In the release build, they should be activated again, so the error pages are displayed. To make things a little easier, I put the registering into a single function, which makes disabling and enabling a little easier.
I hope this explanation clears this issue.

**Comment by kiliankoe** [comment]
Seems very reasonable this way :+1:
